version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - REPOSITORY_URI=$ECR_REPOSITORY_URI
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=$${IMAGE_TAG:-latest}
      - BUILD_NUMBER=$${CODEBUILD_BUILD_NUMBER:-1}
      - echo Build started on `date`
      - echo Building the Docker image for ${service_name}...

  build:
    commands:
      - echo Building Docker image...
      - docker build -t $REPOSITORY_URI:latest ${dockerfile_path}
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$COMMIT_HASH
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:build-$BUILD_NUMBER

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:$COMMIT_HASH
      - docker push $REPOSITORY_URI:build-$BUILD_NUMBER
      - echo Docker images pushed successfully
      - echo "Image URI with latest tag:" $REPOSITORY_URI:latest
      - echo "Image URI with version tag:" $REPOSITORY_URI:$IMAGE_TAG
      - echo "Image URI with commit hash:" $REPOSITORY_URI:$COMMIT_HASH
      - echo "Image URI with build number:" $REPOSITORY_URI:build-$BUILD_NUMBER

artifacts:
  files:
    - '**/*'
  name: ${service_name}-build-artifacts