"""Remove vendor_id from orders table

Revision ID: 2524b9fbfeae
Revises: 639c8e427233
Create Date: 2025-09-15 02:37:20.556626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2524b9fbfeae'
down_revision: Union[str, None] = '639c8e427233'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_product_id'), table_name='inventory')
    op.drop_table('inventory')
    op.drop_table('alembic_version_inventory')
    op.drop_index(op.f('ix_orders_vendor_id'), table_name='orders')
    op.drop_column('orders', 'vendor_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('vendor_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_orders_vendor_id'), 'orders', ['vendor_id'], unique=False)
    op.create_table('alembic_version_inventory',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_inventory_pkc'))
    )
    op.create_table('inventory',
    sa.Column('product_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('available_quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reserved_quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('product_id', name=op.f('inventory_pkey'))
    )
    op.create_index(op.f('ix_inventory_product_id'), 'inventory', ['product_id'], unique=False)
    # ### end Alembic commands ###