name: Trigger CodeBuild on Service Changes

on:
  push:
    branches: [ main ]
    paths:
      - 'services/orders-service/**'
      - 'services/inventory-service/**'

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      orders-changed: ${{ steps.changes.outputs.orders }}
      inventory-changed: ${{ steps.changes.outputs.inventory }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            orders:
              - 'services/orders-service/**'
            inventory:
              - 'services/inventory-service/**'

  trigger-builds:
    needs: detect-changes
    if: needs.detect-changes.outputs.orders-changed == 'true' || needs.detect-changes.outputs.inventory-changed == 'true'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [
          { name: "orders", project: "medisupply-orders-service-build", changed: "${{ needs.detect-changes.outputs.orders-changed }}" },
          { name: "inventory", project: "medisupply-inventory-service-build", changed: "${{ needs.detect-changes.outputs.inventory-changed }}" }
        ]
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Trigger ${{ matrix.service.name }} Service Build
        if: matrix.service.changed == 'true'
        run: |
          echo "🚀 Triggering build for ${{ matrix.service.name }} Service"
          aws codebuild start-build --project-name ${{ matrix.service.project }}

  # Alternative: Always build both services in parallel (uncomment if you want to build both regardless of changes)
  trigger-all-builds:
    if: false  # Set to true to enable building both services always
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [
          { name: "orders", project: "medisupply-orders-service-build" },
          { name: "inventory", project: "medisupply-inventory-service-build" }
        ]
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Trigger ${{ matrix.service.name }} Service Build
        run: |
          echo "🚀 Triggering build for ${{ matrix.service.name }} Service"
          aws codebuild start-build --project-name ${{ matrix.service.project }}